### ISSUE TITLE
`./jager start all` create wrong docker-compose.yml 

### ISSUE THREAD

**Issue by uniray7** [weitingchou/jagereye_ng#39]
when calling './jager start all',
the generated docker-compose.yml will has strange item under 'services':
``` yaml   
base:
        image: "jagereye/base"
        network_mode: ""
        depends_on:
            - database
            - messaging
            - obj_storage
        runtime: nvidia
        environment:
            - JAGERENV=product
```
